name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [22.x]
    steps:
      - uses: action/checkout@v3
      - name: Starting Node.js ${{ matrix.node-varsion}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-varsion}}
        - name: instal modules
          run: npm install
        - name: build project
          run: npm build
        - name: i18:check
          run: i18:check
        - name: storybool
          run: build:storybook
        - name: test--ui
          run: test
